# traefik.yml
api:
  dashboard: true
  insecure: false  # Disable insecure dashboard access

entryPoints:
  web:
    address: ":80"  # HTTP entry point
  web-secure:
    address: ":443"  # HTTPS entry point

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${CF_API_EMAIL}"  # Use Cloudflare email from environment
      storage: "/etc/traefik/acme.json"
      dnsChallenge:
        provider: cloudflare  # Cloudflare DNS challenge
        delayBeforeCheck: 0
        resolvers:
          - "8.8.8.8:53"  # Optional: Google's DNS resolver (can be customized)

providers:
  file:
    filename: "/etc/traefik/traefik.yml"
    directory: "/etc/traefik/dynamic"  # Directory to read dynamic configuration files (optional)
